### ISSUE TITLE
parallel wavenet

### ISSUE THREAD

**Issue by maozhiqiang** [twidddj/tf-wavenet_vocoder#4]
@twidddj ! hi ,  do you plan release parallel wavenet?

**Comment by twidddj** [comment]
Hi @maozhiqiang, thanks to your interest our project! 

Yes, we have a plan to release that part. Currently, we are almost ready to evaluate. 

We hope the part shows up as soon as possible.

**Comment by maozhiqiang** [comment]
hi @twidddj ! thanks for your excellent work, I'm looking forward to seeing the performance of parallel wavenet！

**Comment by neverjoe** [comment]
@twidddj Do you get quality voice now by parallel wavenet?This week, i just can get reasonable voice but still noisy.

**Comment by twidddj** [comment]
Welcome! @neverjoe, we are working to get the reasonable result using distilled parallel wavenet. The student model has just started to learn and the training step is no more than 9K for now. 

If we see some of promising result, The work may be released with a new branch and intermediate results, hopefully in next week . 

I'll open another issue for plan and discussion for parallel wavenet vocoder. Please, come and join us!
