### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by PetrochukM** [twidddj/tf-wavenet_vocoder#6]
Hi There!

Can you release the pre-trained weights used to generate the demo samples?

Thanks!

**Comment by twidddj** [comment]
Hi @PetrochukM, I'll upload it in few days. Thanks!

**Comment by twidddj** [comment]
@PetrochukM, You can download the pre-trained model at [here](https://drive.google.com/file/d/1tptZDDZ8rOWUdse0HWn9W2cm0yN0xhx6) now.

**Comment by PetrochukM** [comment]
Awesome thanks!
