### ISSUE TITLE
local condition cut

### ISSUE THREAD

**Issue by hccho2** [twidddj/tf-wavenet_vocoder#8]
```
condition_cut = tf.shape(local_condition_batch)[1] - tf.shape(conv_filter)[1]
lc = tf.slice(local_condition_batch, [0, condition_cut, 0], [-1, -1, -1])
conv_filter += tf.nn.conv1d(lc, variables['cond_filter'], stride=1, padding="SAME", name="cond_filter")
```

If you cut the local condition before conv1d, the beginning of the local condition is always cut.
I think, the cut should be moved after conv1d.

**Comment by twidddj** [comment]
The cut is natural because It is conducted after dilated convolution for input. ( the n_output would be reduced (n - n_dilation) so the paired condition for the input should be cut before conv1d. don't get confused between dilated conv and conv1d. )
